# vim: ft=ruby:

require 'socket'

Vagrant.configure(2) do |config|

  bdp = is_in_crediteasebdp_env?

  config.vm.define "lain_demo" do |node|

    node.vm.box = "laincloud/centos-lain"
    node.vm.hostname = "lain-demo"

    node.vm.provider "virtualbox" do |v|
      v.memory = 1500
    end

    node.vm.synced_folder "../../", "/vagrant/lain/"

    node.vm.network "private_network", ip: "192.168.77.21"

    if bdp

      node.vm.provision "shell",
        inline: "echo CreditEase bdp env detected, provisioning..."

      node.vm.provision "file",
        source: "../../playbooks/roles/bdp/files",
        destination: "/tmp/bdp-files"

      node.vm.provision "shell",
        path: "../../setup-for-crediteasebdp",
        args: "/tmp/bdp-files"

      node.vm.provision "shell",
        inline: "/vagrant/lain/bootstrap -r docker.bdp.cc:5002 --virtual-ips=192.168.77.201,192.168.77.202,192.168.77.203"

      node.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "shutdown.yaml"
        ansible.install = false
      end

    end

  end

end


def is_in_crediteasebdp_env?
  begin
    TCPSocket.open('mirrors.bdp.idc', 80)
  rescue
    false
  else
    true
  end
end
