# vim: ft=ruby:

require 'socket'

Vagrant.configure(2) do |config|

  bdp = is_in_crediteasebdp_env?

  config.vm.define "lain_demo" do |node|

    node.vm.box = "laincloud/centos"
    node.vm.box_url = [
      "http://10.106.170.108/centos-lain-1460463851.box",
    ]
    node.vm.box_download_checksum_type = 'sha256'
    node.vm.box_download_checksum = '0242a6b1d6bbbba7a7ab3f5ffa5deaf3784be0fdd4e67ad3ab7dc9a8835a1199'
    node.vm.hostname = "lain-demo"

    node.vm.provider "virtualbox" do |v|
      v.memory = 1500
    end

    node.vm.synced_folder "../../", "/vagrant/lain/"

    node.vm.network "private_network", ip: "192.168.77.21"

    if bdp

      node.vm.provision "shell",
        inline: "echo CreditEase bdp env detected, provisioning..."

      node.vm.provision "file",
        source: "../../playbooks/roles/bdp/files",
        destination: "/tmp/bdp-files"

      node.vm.provision "shell",
        inline: "/vagrant/lain/bootstrap -r docker.bdp.cc:5002 --virtual-ips=192.168.77.201,192.168.77.202,192.168.77.203"

    end

  end

end


def is_in_crediteasebdp_env?
  begin
    TCPSocket.open('mirrors.bdp.idc', 80)
  rescue
    false
  else
    true
  end
end
