# vim: ft=ruby:

require 'socket'

Vagrant.configure(2) do |config|

  config.vm.define "lain_demo" do |node|

    node.vm.box = "laincloud/centos-lain"
    node.vm.hostname = "lain-demo"

    node.vm.provider "virtualbox" do |v|
      v.memory = 1500
    end

    node.vm.network "private_network", ip: "192.168.77.21"

    node.vm.provision "shell",
      inline: "/vagrant/lain/bootstrap -r registry.aliyuncs.com/laincloud --virtual-ips=192.168.77.201,192.168.77.202,192.168.77.203"

    node.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "shutdown.yaml"
      ansible.install = false
    end

  end

end
